apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: shipyard-sockshop
spec:
  stages:
  - name: dev
    sequences:
    - name: evaluation
      tasks:
      - name: evaluation 
  - name: hardening
    sequences:
    - name: evaluation
      triggeredOn:
      - dev.evaluation.finished
      tasks:
      - name: evaluation
      - name: release
        
  - name: production
    sequences:
    - name: artifact-delivery 
      triggeredOn:
      - hardening.artifact-delivery.finished
      tasks:
      - name: deployment
        properties:
          strategy: blue_green
      - name: release
      
    - name: remediation
      tasks:
      - name: remediation
      - name: evaluation
